Removing uses of dir::topdown|dir::once
microsoft/rego-cpp pull request #70
Opened 2023-09-09 14:32 UTC by mjp41

The semantics of `dir::topdown|dir::once` is quite complex.  This PR is an experiment to remove its use from rego-cpp. I believe it should be equivalent, but has split a few passes.

2023-09-09 14:34 UTC, mjp41 commented
* [ ] Update comments
* [ ] Separate passes in line with current style
* [ ] Tidy up well-formed definitions

2023-09-11 09:14 UTC, matajoh commented on include/rego/passes.h
> +  PassDef compr1();
I've been trying to keep the names vaguely related to what happens in the past in most cases. Perhaps you can change this to `rules_to_compr`?

2023-09-11 09:15 UTC, matajoh commented on include/rego/passes.h
> +  PassDef skips1();
Similarly, could this be `datarule` or similar?

2023-09-11 09:15 UTC, matajoh requested changes
LGTM

2023-09-11 12:06 UTC, matajoh approved these changes

2023-09-11 12:08 UTC, merged